kappka/app/urls.py
from django.contrib import admin
from django.urls import path, include
from watermeters.views import watermeter_main_view

urlpatterns = [
    path("", watermeter_main_view, name="home"),
    path("vodomery/", include("watermeters.urls")),
    path("admin/", admin.site.urls),
]

kappka/watermeters/urls.py
from django.urls import path
from .views import (
    watermeter_main_view,
    watermeter_detail_view,
    watermeter_detail_hx_view,
)

app_name = "vodomery"
urlpatterns = [
    path("", watermeter_main_view, name="base"),
    path("hx/<str:id>/", watermeter_detail_hx_view, name="hx-detail"),
    path("<str:id>/", watermeter_detail_view, name="detail"),
]

kappka/templates/watermeters/partials/view/cards.html
{% load webpack_loader static %}
{% include "watermeters/filter-sort-form.html" %}
{% load humanize %}


<div id="cards-view" class="text-center">
    {% if queryset %}
        <div class="row row-cols-lg-3 row-cols-md-2 row-cols-1 g-4">
            {% for object in queryset %}
                    {% if object.id %}
                        <div class="col">
                            <div class="card border border-2 border-primary rounded-4 h-100">
                                <div class="card-body py-4">
                                    <div class="card-title m-0 text-primary d-inline-flex align-items-center">
                                        {% if object.hourly_consumption is not none %}
                                            <svg class="me-2 drop-icon"><use href="{% static 'vendors/images/drop.svg' %}#drop"></use></svg>
                                            <span class="display-5 fw-bold me-2">{{ object.hourly_consumption|intcomma }}</span>
                                            <span class="fs-5 fw-semibold">l/hod</span>
                                        {% else %}
                                            <span class="display-5 fw-bold">–⁠</span>
                                        {% endif %}
                                    </div>
                                    <h6 class="card-subtitle"><a href="{{ object.get_absolute_url }}" class="text-dark text-decoration-none stretched-link d-inline-flex justify-content-center align-items-center fs-5 fw-semibold mt-2 mb-3">{% if object.name is not None%}{{ object.name|upper }}{% else %}{{ object.id }}{% endif %}<svg class="ms-2 status-fill-colors-{{ object.status.name|lower }}"><use href="{% static 'vendors/images/circle.svg' %}#circle"></use></svg></a></h6>
                                    <ul class="list-unstyled">
                                        <li><span class="fw-semibold">Stav vodoměru:</span> {% if object.last_record_value is not none %}{{ object.last_record_value|intcomma }}{% else %}–{% endif %} l</li>
                                        <li><span class="fw-semibold">Denní spotřeba:</span> {% if object.daily_consumption is not none %}{{ object.daily_consumption|intcomma }}{% else %}–{% endif %} l</li>
                                        <li><span class="fw-semibold">Poslední aktualizace:</span> {% if object.last_record_time is not none %}{{ object.last_record_time|naturaltime }}{% else %}–{% endif %}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <p>Nebyly nalezeny žádné výsledky.</p>
    {% endif %}
</div>

kappka/templates/watermeters/partials/view/home.html
{% load webpack_loader static %}
{% include "watermeters/filter-sort-form.html" %}
{% load humanize %}


<div id="home-view" class="text-center">
    {% if queryset %}
        <button hx-get='{% url "vodomery:base" %}' hx-target="#base-view" hx-push-url="true" hx-include="[name='f'], [name='q'], [name='s'], [name='v']" class="btn btn-primary rounded-5 px-4 mb-5 fw-semibold">Zobrazit všechny vodoměry</button>
        <h2 class="my-5 text-uppercase fw-bold">Vodoměry s největším průtokem</h2>
        <div class="row g-5">
            {% for object in queryset %}
                    {% if object.id %}
                        <div class="col">
                            <div class="card border-0 bg-transparent h-100">
                                <div class="position-relative">
                                    <svg class="drop-icon-home card-img-top"><use href="{% static 'vendors/images/drop.svg' %}#drop"></use></svg>
                                    <div class="drop-text position-absolute start-50 translate-middle">
                                        <h4 class="text-primary fs-1 fw-bold m-0">{% if object.hourly_consumption is not none %}{{ object.hourly_consumption|intcomma }}{% else %}?{% endif %}</h4>
                                        <h5 class="m-0">l/hod</h5>
                                    </div>
                                </div>
                                <div class="card-body mt-2 pb-0">
                                    <h3 class="card-title fs-4 fw-semibold">{% if object.name is not None%}{{ object.name|upper }}{% else %}{{ object.id }}{% endif %}</h3>
                                </div>
                                <div class="card-footer bg-transparent border-0"><a href="{{ object.get_absolute_url }}" class="btn btn-primary border border-primary rounded-5 px-4 fw-semibold">Podrobný přehled</a></div>
                            </div>
                        </div>
                    {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <p>Nebyly nalezeny žádné výsledky.</p>
    {% endif %}
</div>

kappka/templates/watermeters/partials/view/map.html
{% include "watermeters/filter-sort-form.html" %}


<div id="map-view" class="text-center">
    {% if map %}
        {{ map|safe }}
    {% else %}
        <p>Nebyly nalezeny žádné výsledky.</p>
    {% endif %}
</div>

kappka/templates/watermeters/partials/view/table.html
{% include "watermeters/filter-sort-form.html" %}
{% load webpack_loader static %}
{% load humanize %}


<div id="table-view" class="text-center table-responsive">
    {% if queryset %}
        <table class="table table-hover">
            <thead class="border-bottom border-primary border-2">
                <tr>
                  <th scope="col">Název</th>
                  <th scope="col">Stav vodoměru (l)</th>
                  <th scope="col">Denní spotřeba (l/den)</th>
                  <th scope="col">Aktuální spotřeba (l/hod)</th>
                  <th scope="col">Poslední aktualizace</th>
                </tr>
              </thead>
              <tbody>
                {% for object in queryset %}
                <tr class="border-bottom border-secondary position-relative text-nowrap"> 
                    {% if object.id %}
                        <th scope="row"><a href="{{ object.get_absolute_url }}" class="stretched-link text-dark text-decoration-none d-inline-flex justify-content-center align-items-center fw-semibold">{% if object.name is not None%}{{ object.name|upper }}{% else %}{{ object.id }}{% endif %}<svg class="ms-2 status-fill-colors-{{ object.status.name|lower }}"><use href="{% static 'vendors/images/circle.svg' %}#circle"></use></svg></a></th>
                        <td>{{ object.last_record_value|intcomma }}</td>
                        <td>{% if object.daily_consumption is not none %}{{ object.daily_consumption|intcomma }}{% else %}–{% endif %}</td>
                        <td>{% if object.hourly_consumption is not none %}{{ object.hourly_consumption|intcomma }}{% else %}–{% endif %}</td>
                        <td>{{ object.last_record_time|naturaltime }}</td>
                    {% endif %}
                </tr>
                {% endfor %}
              </tbody>
        </table>
    {% else %}
        <p>Nebyly nalezeny žádné výsledky.</p>
    {% endif %}
</div>